name: Build and deploy container

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  find-targets:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v3
      - id: find-targets
        run: |
          content=$(cat docker-bake.hcl | grep target | grep root | sed 's/target "\(.*\)".*/"\1"/' | grep -v -e "debian_\(non\)\?root" -e "ubuntu_\(non\)\?root" -e "alpine_\(non\)\?root" | tr '\n' ',' | sed 's/,*$//')
          echo "targets=[$content]" >> ${GITHUB_OUTPUT}
    outputs:
      targets: ${{ steps.find-targets.outputs.targets }}

  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    needs:
      - find-targets

    strategy:
      matrix:
        target: ${{ fromJSON(needs.find-targets.outputs.targets) }}

    steps:
      # Free some spaces to avoid "No space left on device" error
      # https://github.com/actions/runner-images/issues/2840
      - name: Free spaces
        run: |
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf ${AGENT_TOOLSDIRECTORY}
          sudo docker rmi $(docker image ls -aq) || true

      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.target }}
        uses: docker/bake-action@v3
        with:
          push: true
          targets: ${{ matrix.target }}
