name: Build and deploy container

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  find-targets:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      - id: find-targets
        run: |
          content=$(cat docker-bake.hcl | grep target | grep root | sed 's/target "\(.*\)".*/"\1"/' | tr '\n' ',' | sed 's/,*$//')
          echo "targets=[$content]" >> ${GITHUB_OUTPUT}
    outputs:
      targets: ${{ steps.find-targets.outputs.targets }}

  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    needs:
      - find-targets

    timeout-minutes: 1440

    strategy:
      matrix:
        target: ${{ fromJSON(needs.find-targets.outputs.targets) }}

    steps:
      # Free some spaces to avoid "No space left on device" error
      # https://github.com/actions/runner-images/issues/2840
      # https://github.com/easimon/maximize-build-space
      - name: Free some spaces
        run: |
          echo "Available storage:"
          df -h
          echo
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /hostedtoolcache/CodeQL
          sudo rm -rf $AGENT_TOOLSDIRECTORY
          sudo docker image prune --all --force
          echo "Available storage:"
          df -h
          echo

      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        timeout-minutes: 1440

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.target }}
        uses: docker/bake-action@v5
        with:
          push: true
          targets: ${{ matrix.target }}
