name: Build and deploy container

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'

concurrency:
  group: "package"
  cancel-in-progress: false

env:
  REGISTRY: ghcr.io

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
            arch_name: amd64
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
            arch_name: arm64
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read

    steps:
      # Free some spaces to avoid "No space left on device" error
      # https://github.com/actions/runner-images/issues/2840
      # https://github.com/easimon/maximize-build-space
      - name: Free some spaces
        run: |
          echo "Available storage:"
          df -h
          echo
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /hostedtoolcache/CodeQL
          sudo rm -rf $AGENT_TOOLSDIRECTORY
          sudo docker image prune --all --force
          echo "Available storage:"
          df -h
          echo

      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.arch_name }}
        uses: docker/bake-action@v6
        with:
          set: |
            latest.platform=${{ matrix.platform }}
            latest.tags=local/latex-devcontainer:${{ matrix.arch_name }}
            latest.load=true

      - name: Clean up build cache
        run: |
          docker image prune --force
          docker builder prune --force
          docker system prune --volumes --force
          echo "Available storage:"
          df -h
          echo

      - name: Export image ${{ matrix.arch_name }} to tar
        run: |
          docker save -o /tmp/image-${{ matrix.arch_name }}.tar local/latex-devcontainer:${{ matrix.arch_name }}

      - name: Split ${{ matrix.arch_name }} image
        run: |
          split -b 2G /tmp/image-${{ matrix.arch_name }}.tar /tmp/image-${{ matrix.arch_name }}.tar.part.
          ls -la /tmp/image-${{ matrix.arch_name }}.tar.part.*

      - name: Upload ${{ matrix.arch_name }} artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-${{ matrix.arch_name }}
          path: /tmp/image-${{ matrix.arch_name }}.tar.part.*

  create-manifest:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Free some spaces
        run: |
          echo "Available storage:"
          df -h
          echo
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /hostedtoolcache/CodeQL
          sudo rm -rf $AGENT_TOOLSDIRECTORY
          sudo docker image prune --all --force
          echo "Available storage:"
          df -h
          echo

      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:qemu-v9.2.2
      - uses: docker/setup-buildx-action@v3

      - name: Download AMD64 artifacts
        uses: actions/download-artifact@v4
        with:
          name: docker-image-amd64
          path: /tmp/amd64/

      - name: Reassemble AMD64 image
        run: |
          cat /tmp/amd64/image-amd64.tar.part.* > /tmp/image-amd64.tar
          docker load -i /tmp/image-amd64.tar
          rm -rf /tmp/amd64/ /tmp/image-amd64.tar

      - name: Download ARM64 artifacts
        uses: actions/download-artifact@v4
        with:
          name: docker-image-arm64
          path: /tmp/arm64/

      - name: Reassemble ARM64 image
        run: |
          cat /tmp/arm64/image-arm64.tar.part.* > /tmp/image-arm64.tar
          docker load -i /tmp/image-arm64.tar
          rm -rf /tmp/arm64/ /tmp/image-arm64.tar

      - name: Create merged manifest
        run: |
          docker manifest create local/latex-devcontainer:built \
            --amend local/latex-devcontainer:amd64 \
            --amend local/latex-devcontainer:arm64

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push multi-arch manifest using OCI cache
        uses: docker/bake-action@v6
        with:
          push: true
          set: |
            latest.dockerfile-inline="FROM local/latex-devcontainer:built"
            
