name: Build and deploy container

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # - name: Build alpine
      #   uses: docker/bake-action@v3
      #   with:
      #     push: true
      #     targets: alpine

      # - name: Build ubuntu
      #   uses: docker/bake-action@v3
      #   with:
      #     push: true
      #     targets: ubuntu

      - name: Build debian
        uses: docker/bake-action@v3
        with:
          push: true
          targets: debian    

      - name: Build latest
        uses: docker/bake-action@v3
        with:
          push: true
          targets: latest
