name: Build and deploy container

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'

concurrency:
  group: "package"
  cancel-in-progress: false

env:
  REGISTRY: ghcr.io

jobs:
  find-targets:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      - uses: docker/bake-action/subaction/matrix@v6
        id: find-targets
        with:
          target: default

    outputs:
      targets: ${{ steps.find-targets.outputs.targets }}

  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    needs:
      - find-targets

    strategy:
      matrix:
        target: ${{ fromJSON(needs.find-targets.outputs.targets) }}

    steps:
      # Free some spaces to avoid "No space left on device" error
      # https://github.com/actions/runner-images/issues/2840
      # https://github.com/easimon/maximize-build-space
      - name: Free some spaces
        run: |
          echo "Available storage:"
          df -h
          echo
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /hostedtoolcache/CodeQL
          sudo rm -rf $AGENT_TOOLSDIRECTORY
          sudo docker image prune --all --force
          echo "Available storage:"
          df -h
          echo

      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:qemu-v9.2.0
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.target }}
        uses: docker/bake-action@v6
        with:
          push: true
          targets: ${{ matrix.target }}
